-- ==========================================
-- UNIEVENT CONNECT: PRODUCTION-READY MASTER SETUP
-- ==========================================
-- This script handles all table creations, enhancements, 
-- storage, RLS, and Real-time with specific business logic:
-- 1. Auto-verified universities
-- 2. Registered-only chat access

-- 1. EXTENSIONS
-- ==========================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. BASE TABLES
-- ==========================================

-- Universities Table
CREATE TABLE IF NOT EXISTS public.universities (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text UNIQUE NOT NULL,
  email_domain text,
  six_digit_key text,
  admin_email text,
  is_verified boolean DEFAULT true, -- USER: Auto-verified by default
  created_at timestamp with time zone DEFAULT now()
);

-- Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY, -- References auth.users(id)
  email text,
  role text DEFAULT 'student',
  university_id uuid REFERENCES public.universities(id) ON DELETE SET NULL,
  university_name text,
  status text DEFAULT 'pending',
  display_name text,
  full_name text,
  phone text,
  degree text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now()
);

-- Events Table
CREATE TABLE IF NOT EXISTS public.events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  category text,
  date date NOT NULL,
  end_date date,
  start_time time,
  end_time time,
  deadline date,
  venue text,
  description text,
  poster_url text,
  reg_link text,
  admin_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  university_id uuid REFERENCES public.universities(id) ON DELETE CASCADE,
  form_blueprint jsonb DEFAULT '[]'::jsonb,
  chat_locked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Registrations Table
CREATE TABLE IF NOT EXISTS public.registrations (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id bigint REFERENCES public.events(id) ON DELETE CASCADE,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  student_email text,
  student_name text,
  form_response jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(event_id, student_id)
);

-- Event Chats Table
CREATE TABLE IF NOT EXISTS public.event_chats (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id bigint REFERENCES public.events(id) ON DELETE CASCADE,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  sender_name text NOT NULL,
  message text NOT NULL,
  is_admin boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Muted Users Table
CREATE TABLE IF NOT EXISTS public.muted_users (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  event_id bigint REFERENCES public.events(id) ON DELETE CASCADE,
  student_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  muted_by uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(event_id, student_id)
);

-- 3. STORAGE SETUP
-- ==========================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('event-posters', 'event-posters', true)
ON CONFLICT (id) DO NOTHING;

-- 4. ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS on all tables
ALTER TABLE public.universities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_chats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.muted_users ENABLE ROW LEVEL SECURITY;

-- 4a. Universities Policies
DROP POLICY IF EXISTS "Public universities access" ON public.universities;
CREATE POLICY "Public universities access" ON public.universities FOR SELECT TO public USING (true);

DROP POLICY IF EXISTS "Allow authenticated to insert universities" ON public.universities;
CREATE POLICY "Allow authenticated to insert universities" ON public.universities FOR INSERT TO authenticated WITH CHECK (true);

-- 4b. Profiles Policies
DROP POLICY IF EXISTS "Public profile select" ON public.profiles;
CREATE POLICY "Public profile select" ON public.profiles FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Profiles insertion" ON public.profiles;
CREATE POLICY "Profiles insertion" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);

-- 4c. Events Policies
DROP POLICY IF EXISTS "Events select access" ON public.events;
CREATE POLICY "Events select access" ON public.events FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Admin events full control" ON public.events;
CREATE POLICY "Admin events full control" ON public.events FOR ALL TO authenticated USING (true); 

-- 4d. Registrations Policies
DROP POLICY IF EXISTS "Student can see own registrations" ON public.registrations;
CREATE POLICY "Student can see own registrations" ON public.registrations FOR SELECT TO authenticated USING (auth.uid() = student_id OR EXISTS (
    SELECT 1 FROM public.events WHERE id = registrations.event_id AND admin_id = auth.uid()
));

DROP POLICY IF EXISTS "Student registration insert" ON public.registrations;
CREATE POLICY "Student registration insert" ON public.registrations FOR INSERT TO authenticated WITH CHECK (auth.uid() = student_id);

-- 4e. Event Chats Policies (RESTRICTED TO REGISTERED STUDENTS)
DROP POLICY IF EXISTS "Allow authenticated selects chats" ON public.event_chats;
CREATE POLICY "Allow authenticated selects chats" ON public.event_chats FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Allow registered students to chat" ON public.event_chats;
CREATE POLICY "Allow registered students to chat" ON public.event_chats 
FOR INSERT TO authenticated 
WITH CHECK (
  -- 1. Check if user is registered student
  EXISTS (
    SELECT 1 FROM public.registrations 
    WHERE registrations.event_id = event_chats.event_id 
    AND registrations.student_id = auth.uid()
  ) 
  OR 
  -- 2. OR check if user is the admin of the event
  EXISTS (
    SELECT 1 FROM public.events
    WHERE events.id = event_chats.event_id
    AND events.admin_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Allow admin deletes chat" ON public.event_chats;
CREATE POLICY "Allow admin deletes chat" ON public.event_chats FOR DELETE TO authenticated USING (EXISTS (
    SELECT 1 FROM public.events WHERE id = event_chats.event_id AND admin_id = auth.uid()
));

-- 4f. Muted Users Policies
DROP POLICY IF EXISTS "View muted status" ON public.muted_users;
CREATE POLICY "View muted status" ON public.muted_users FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Admin moderation control" ON public.muted_users;
CREATE POLICY "Admin moderation control" ON public.muted_users FOR ALL TO authenticated USING (EXISTS (
    SELECT 1 FROM public.events WHERE id = muted_users.event_id AND admin_id = auth.uid()
));

-- 5. REAL-TIME CONFIGURATION
-- ==========================================

DO $$
BEGIN
    -- Enable real-time for muted_users
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'muted_users') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.muted_users;
    END IF;

    -- Enable real-time for event_chats
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'event_chats') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.event_chats;
    END IF;

    -- Enable real-time for events
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'events') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.events;
    END IF;

    -- Enable real-time for profiles
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'profiles') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
    END IF;

    -- Enable real-time for registrations
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'registrations') THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.registrations;
    END IF;
END $$;

-- Ensure FULL replica identity for all tracked tables
ALTER TABLE public.muted_users REPLICA IDENTITY FULL;
ALTER TABLE public.event_chats REPLICA IDENTITY FULL;
ALTER TABLE public.events REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER TABLE public.registrations REPLICA IDENTITY FULL;
